// Auto-generated by `npm run gen:types`. Safe to edit for placeholders; regenerate after backend changes.

export interface components {
  schemas: {
    RmnItem: {
      id?: string;
      title?: string;
      description?: string;
    };
  };
}

export type RmnItem = components["schemas"]["RmnItem"];
